### ISSUE TITLE
Lack of separation of concerns in API architecture.  

### ISSUE THREAD

**Issue by kaveeshbhashitha** [kavineksith/Insophinia-Management-API-with-Node-JS#1]
The current architecture of our API lacks a crucial separation of concerns. While it follows an MVC pattern, it entirely bypasses the inclusion of models, relying solely on controllers with integrated model functions. This not only violates the fundamental principle of modularity but also poses security risks by consolidating too much responsibility within controllers.

**Comment by kavineksith** [comment]
Thank you for bringing this issue to our attention. It's crucial for the long-term sustainability and security of our API that we address these architectural concerns. Your proposed solution to introduce standalone models and integrate them into our existing MVC architecture is commendable.

We acknowledge the importance of this enhancement and will prioritize its implementation. By separating concerns and adhering more closely to the MVC pattern, we anticipate significant improvements in both security and maintainability.

Your efforts in identifying and providing a solution to this issue are greatly appreciated.
